language: python

python:
    - "3.5.1"

install: 
    - pip install -r requirement/development.txt

services:
    - postgresql

before_script:
    - createuser hanminsoo
    - psql -c 'create database bookconnect;' -U hanminsoo

# # command to run tests
script:
    - pep8
    - python wef/manage.py test users
