language: python

python:
    - "3.5.1"
addons:
    postgresql:"9.5.1"

install: 
    - pip install -r requirement/development.txt

before_script:
    - psql -c 'CREATE DATABASE bookconnect;' -U postgres
    - psql -c 'CREATE USER hanminsoo WITH PASSWORD "deadlylaid";' -U postgres
    - psql -c 'GRANT ALL PRIVILEGES ON DATABASE bookconnect TO deadlylaid;' - U postgres

# # command to run tests
script:
    - pep8
    - python wef/manage.py makemigrations users items
    - python wef/manage.py migrate
    - python wef/manage.py test functional_test
