language: python

python:
    - "3.5.1"

install: 
    - pip install -r requirement/development.txt

before_script:
    - sudo psql -c  'create database bookconnect' -U postgres
    - createuser hanminsoo

# # command to run tests
script:
    - pep8
    - python wef/manage.py test functional_test
