language:
    python
python:
    - 3.5.1
addons:
    postgresql:"9.5.1"
install:
    - pip install -r requirement/development.txt
before_script:
    - psql -c 'CREATE DATABASE bookconnect;' -U postgres
    - createuser hanminsoo
    - psql -c 'GRANT ALL PRIVILEGES ON DATABASE bookconnect TO hanminsoo;' -U postgres
    - psql -c 'ALTER USER hanminsoo CREATEDB;' -U postgres
    - npm -g install yuglify
    - npm install yuglify
    - redis-server --port 6378 --requirepass 'secret'

# # command to run tests
script:
    - pep8
    - python wef/manage.py makemigrations users items
    - python wef/manage.py migrate
    - python wef/manage.py collectstatic --settings=wef.settings.development --noinput
    - python wef/manage.py test users items --settings=wef.settings.development
